import './globals.css'
import Footer from './homePage/Footer'
import Header from './homePage/Header'

export const metadata = {
  title: 'PIAIC Website',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
